package com.sherry.mapper;

import com.sherry.model.User;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Nov 21 16:58:07 CST 2016
     */
    public int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Nov 21 16:58:07 CST 2016
     */
    public int insert(User record);

    public List<Map> listUser();

}